echo "Testing accessibility within SCRIPT"
echo "DOTENV value in the script is ${DOTENV}"
echo "DOTENVVARFORWARD value in script is ${DOTENVVARFORWARD}"
echo "SHELLVARFORWARD value in the script ${SHELLVARFORWARD}"
echo "SHELLVARFORWARDWITHDEFAULT value in the script ${SHELLVARFORWARDWITHDEFAULT}"
echo "SHELLVAR value in the script is ${SHELLVAR}"
echo "COMMONVAR value in the script is ${COMMONVAR}"
echo "ENVFILE value in the script is ${ENVFILE}"
echo "DOCKERFILEENV value in the script is ${DOCKERFILEENV}"
SECRET=$(cat /run/secrets/file_secret)
echo "SECRET value parsed in the script is ${SECRET}"
#echo "UNCOMMONVAR value in script is ${UNCOMMONVAR}"
